import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Download, FileText, Loader2 } from "lucide-react";
import { motion } from "framer-motion";
import { format } from "date-fns";

export const CustomReports = ({ project, analytics, services }) => {
  const [generating, setGenerating] = useState(false);
  const [selections, setSelections] = useState({
    security: true,
    api: true,
    cicd: true,
    tasks: true,
    trends: false,
    recommendations: true
  });

  const generateReport = async () => {
    setGenerating(true);
    
    let report = `# ${project.name} - Analytics Report
**Generated:** ${format(new Date(), 'PPpp')}

---

## Executive Summary

**Project:** ${project.name}
**Category:** ${project.category}
**Services:** ${services.length}
**Status:** ${project.status}

---
`;

    if (selections.security) {
      const securityMetrics = {
        total: analytics.security.length,
        critical: analytics.security.filter(f => f.severity === 'critical').length,
        open: analytics.security.filter(f => f.status === 'open').length
      };

      report += `
## Security Overview

- **Total Findings:** ${securityMetrics.total}
- **Critical:** ${securityMetrics.critical}
- **Open Issues:** ${securityMetrics.open}

### Recent Critical Findings
${analytics.security
  .filter(f => f.severity === 'critical')
  .slice(0, 5)
  .map(f => `- **${f.title}** (${f.source}): ${f.description}`)
  .join('\n')}

---
`;
    }

    if (selections.api) {
      const apiMetrics = {
        total: analytics.api.integrations?.length || 0,
        active: analytics.api.integrations?.filter(a => a.status === 'active').length || 0
      };

      report += `
## API Performance

- **Total Integrations:** ${apiMetrics.total}
- **Active:** ${apiMetrics.active}

### API List
${analytics.api.integrations?.map(api => 
  `- **${api.name}**: ${api.metrics?.total_requests || 0} requests, ${api.metrics?.avg_response_time || 0}ms avg response`
).join('\n') || 'No APIs configured'}

---
`;
    }

    if (selections.cicd) {
      report += `
## CI/CD Configuration

- **Pipelines Configured:** ${analytics.cicd.length}
${analytics.cicd.map(c => `- **${c.platform}**: ${c.deployment_targets?.length || 0} targets`).join('\n')}

---
`;
    }

    if (selections.tasks) {
      const taskMetrics = {
        total: analytics.tasks.length,
        completed: analytics.tasks.filter(t => t.status === 'completed').length,
        inProgress: analytics.tasks.filter(t => t.status === 'in_progress').length
      };

      report += `
## Task Management

- **Total Tasks:** ${taskMetrics.total}
- **Completed:** ${taskMetrics.completed}
- **In Progress:** ${taskMetrics.inProgress}
- **Completion Rate:** ${((taskMetrics.completed / taskMetrics.total) * 100).toFixed(1)}%

---
`;
    }

    if (selections.recommendations) {
      report += `
## Recommendations

### Security
- Review and remediate critical findings immediately
- Implement automated security scanning in CI/CD
- Regular penetration testing schedule

### Performance
- Optimize API response times for endpoints >500ms
- Implement caching strategies for frequently accessed data
- Monitor and scale based on traffic patterns

### Operations
- Increase test coverage for critical services
- Document deployment procedures
- Establish incident response protocols

---
`;
    }

    report += `
## Appendix

**Report Sections Included:**
${Object.entries(selections).filter(([k, v]) => v).map(([k]) => `- ${k}`).join('\n')}

**Generated by:** ArchDesigner Analytics Platform
`;

    // Download
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project.name}-analytics-${format(new Date(), 'yyyy-MM-dd')}.md`;
    a.click();
    URL.revokeObjectURL(url);

    setGenerating(false);
  };

  return (
    <div className="space-y-6">
      <Card className="bg-gradient-to-r from-blue-50 to-indigo-50 border-2 border-blue-200">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-blue-600" />
            Custom Report Generator
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="grid md:grid-cols-3 gap-4">
            {Object.entries(selections).map(([key, value]) => (
              <div key={key} className="flex items-center space-x-2">
                <Checkbox
                  id={key}
                  checked={value}
                  onCheckedChange={(checked) => setSelections({...selections, [key]: checked})}
                />
                <Label htmlFor={key} className="capitalize cursor-pointer">
                  {key.replace('_', ' ')}
                </Label>
              </div>
            ))}
          </div>

          <Button onClick={generateReport} disabled={generating} className="w-full" size="lg">
            {generating ? <Loader2 className="w-5 h-5 mr-2 animate-spin" /> : <Download className="w-5 h-5 mr-2" />}
            Generate & Download Report
          </Button>
        </CardContent>
      </Card>

      <div className="grid md:grid-cols-2 gap-6">
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }}>
          <Card className="shadow-lg">
            <CardHeader className="bg-gradient-to-r from-purple-50 to-pink-50">
              <CardTitle className="text-lg">Report Formats</CardTitle>
            </CardHeader>
            <CardContent className="p-6">
              <ul className="space-y-2 text-sm">
                <li className="flex items-center gap-2">
                  <FileText className="w-4 h-4 text-purple-600" />
                  Markdown (.md)
                </li>
                <li className="flex items-center gap-2 text-gray-400">
                  <FileText className="w-4 h-4" />
                  PDF (Coming Soon)
                </li>
                <li className="flex items-center gap-2 text-gray-400">
                  <FileText className="w-4 h-4" />
                  Excel (Coming Soon)
                </li>
              </ul>
            </CardContent>
          </Card>
        </motion.div>

        <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }}>
          <Card className="shadow-lg">
            <CardHeader className="bg-gradient-to-r from-blue-50 to-cyan-50">
              <CardTitle className="text-lg">Report Contents</CardTitle>
            </CardHeader>
            <CardContent className="p-6">
              <ul className="space-y-2 text-sm text-gray-700">
                <li>✓ Executive summary with key metrics</li>
                <li>✓ Security findings and posture</li>
                <li>✓ API performance analytics</li>
                <li>✓ CI/CD configuration status</li>
                <li>✓ Task management metrics</li>
                <li>✓ AI-powered recommendations</li>
              </ul>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
};